#!/usr/bin/env python3
"""
Plot psychometric curves from fixed MOCS stimuli experimental data.

This script analyzes data files created using the fixed MOCS stimuli
(generated by make_mocs_stimuli_fixed) and creates psychometric plots
showing the probability of left/right responses at different tilt angles
for each surround condition (positive, negative, no surround).
"""

import staircase_to_stimuli as ss
import os
import glob

def plot_single_subject(csv_path, output_dir=None):
    """Plot psychometric curves for a single subject's data file."""
    if output_dir is None:
        # Create plots subdirectory next to the data file
        output_dir = os.path.join(os.path.dirname(csv_path), 'plots')
    
    print(f"Processing: {csv_path}")
    results = ss.plot_fixed_mocs_from_csv(
        csv_path,
        output_dir=output_dir,
        fit=True,
        model='logistic2'
    )
    
    print(f"  Plots saved to: {output_dir}")
    for surr_type, path in results.items():
        print(f"    {surr_type}: {os.path.basename(path)}")
    
    return results

def plot_all_subjects(data_dir='tilt_mocs/data'):
    """Plot psychometric curves for all subjects in the data directory."""
    # Find all CSV files in subject directories
    pattern = os.path.join(data_dir, 'sub-*/ses-*/sub-*_exp-tiltmocs_*.csv')
    csv_files = glob.glob(pattern)
    
    if not csv_files:
        print(f"No data files found matching pattern: {pattern}")
        return
    
    print(f"Found {len(csv_files)} data file(s)\n")
    
    for csv_path in csv_files:
        try:
            plot_single_subject(csv_path)
            print()
        except Exception as e:
            print(f"  Error: {e}\n")

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        # Plot specific file
        csv_path = sys.argv[1]
        plot_single_subject(csv_path)
    else:
        # Plot all subjects
        plot_all_subjects()
